<?php 
/**
 * View -- of Academic/CurriculumController/addstudentlist
 * chophel@athang.com
 */
$this->headTitle($this->title);
foreach($studentlist as $studentlists);
// print_r($studentlists);
// exit;

?>
<form id="#form" method="post" action="<?php echo $this->url('curriculum', array('action' => 'addstudentlist','id'=>$page)); ?>"  enctype="multipart/form-data" >                  
<div class="modal-header">
        <h5 class="modal-title"><i class="ace-icon fa fa-plus-square-o"></i> <?php echo $this->title;?></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>  <!-- /modal-header -->
    <div class="modal-body">
		<div class="panel panel-default">
			<div class="panel-body">   
				<div class="row">
					<input type="hidden" name="academic_year" value="<?php echo $studentlists['academic_year'];?>">
					<input type="hidden" name="batch" value="<?php echo $studentlists['batch'];?>">
					<input type="hidden" name="organization" value="<?php echo $studentlists['organization'];?>">
					<input type="hidden" name="class" value="<?php echo $studentlists['class_name'];?>">
					<input type="hidden" name="course" value="<?php echo $studentlists['course'];?>">
					<input type="hidden" name="program" value="<?php echo $studentlists['program'];?>">
					<input type="hidden" name="id" value="<?php echo $studentlists['id'];?>">
					<div class="form-group col-lg-12">  
						<label class="control-label" for="district">Student</label>
						<select id="student" name="student" class="form-control" data-placeholder="Select">
							<option value="-1" selected>None</option>
							<?php foreach($this->student->get(array('staff'=>1,'organization'=>$studentlists['organization'])) as $students):?>
								<option value="<?php echo $students['id']?>">
									<?php echo $students['full_name'];?>/<?php echo $students['cid'];?></option>
							<?php endforeach;?>
						</select>
					</div>
				</div>
			</div>
		</div>
	</div> <!-- /modal-body -->    
    <div class="modal-footer">
		<button type="submit" class="btn btn-success"><i class="ace-icon fa fa-check"></i>Save</button>
        <button type="button" class="btn btn-warning" data-dismiss="modal"><i class="ace-icon fa fa-times"></i>Cancel</button> 
    </div>
</form>
<script>
$(function(){
	const fv = FormValidation.formValidation(document.getElementById('#form'), {
		fields: {
			student: {
				validators: {
					notEmpty: {
						message: 'Please select student.'
					}
				}
			},
			
		},
		plugins: {
			trigger: new FormValidation.plugins.Trigger(),
			bootstrap3: new FormValidation.plugins.Bootstrap3(),
			submitButton: new FormValidation.plugins.SubmitButton(),
			defaultSubmit: new FormValidation.plugins.DefaultSubmit(),
		},
	}).on('core.element.validated', function (e) {
		if (e.valid) {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-invalid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-valid');
		} else {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-valid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-invalid');
		}
	});
	$('form select').chosen().change(function () {
		fv.revalidateField($(this).attr('name'));
	});
});
</script>