<?php
/**
 * View -- of Administration/DomainController/viewcurriculum
 * chophel@athang.com
 */
	$this->headTitle($this->title);
	foreach($organization as $row);
	//print_r($row);
	 //exit;
	extract($row);

?>
<?php echo $this->tabs_helper(array(2831)); ?>
<div class="card">
	<div class="card-header">
		<?php echo $this->button(2,$id);?>
	</div>
	<div class="table-responsive">
	<table id="datatable" class="d-style w-100 table text-dark-m1 text-95 border-y-1 brc-black-tp11 collapsed dtr-table">
                  <!-- add `collapsed` by default ... it will be removed by default -->
                  <!-- thead with .sticky-nav -->
         <thead class="sticky-nav text-primary-d1 text-uppercase text-100">
				<tr>
					<th>#</th>
					<th>Class Name
					<th>Academic Year</th>
					<th>Organization</th>
					<th>Level</th>
					<th>Program</th>
					<th>Batch</th>
					<?php if($this->button(1)!=""):?>
						<th class="no-sort no-printpdf">Action</th>
					<?php endif;?>	
				</tr>
			</thead>
			<tbody>
			<?php 
				$i=1;
				foreach ($paginator as $row):?>
				
				<tr data-href="<?php echo $this->button(4,$row['id']); ?>">
					<td><?php  echo $i++; ?></td>	
					<td ><?php  echo $row['class_name']; ?></td>	
					<td><?php  echo $row['academic_year']; ?></td>	
					<td class="uchen"><?php  echo $this->org->getColumn($row['organization'],'location'); ?></td>	
					<td class="uchen"><?php  echo $this->classes->getColumn($row['level'],'standard'); ?></td>		
					<td class="uchen"><?php  echo $this->program->getColumn($row['program'],'name'); ?></td>	
					<td><?php  echo $row['batch']; ?></td>							
					<?php if($this->button(1)!=""):?>
						<td><?php echo $this->button(1, $row['id'].'_'.$page);?></td>
					<?php endif;?>
				</tr>
				<?php endforeach; ?>
			</tbody>
		</table>
	</div>
	<div class="card-footer d-flex align-items-center">
		<?php echo $this->paginationControl($this->paginator,'Sliding','adm_pagination.phtml', 
			array('route' => 'curriculum/paginator','action'=>'initiateacademic','id'=>'0'));?>
	</div>
</div>
<div class="modal fade" id="modal" tabindex="-1" role="dialog" aria-hidden="true">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
		</div><!-- /.modal-content -->
	</div><!-- /.modal-dialog -->
</div><!-- /.modal -->
<script>
$(function(){
	// $('select#district').on('change',function(){
	// 		$.post(
	// 			"<?php echo $this->url('monk', array('action' => 'getorganization'));?>",
	// 			{
	// 				rdzoId: $(this).val(),
	// 			},
	// 			function(data){
	// 				$('select#organization').html(data.organization);
	// 				$('select#organization').trigger('chosen:updated');
	// 			},
	// 			'json'
	// 		);
	// 	});
		const fv = FormValidation.formValidation(document.getElementById('#form'), {
		fields: {
			academic_year: {
				validators: {
					notEmpty: {
						message: 'Please select academic year.'
					}
				}
			},
			district: {
				validators: {
					notEmpty: {
						message: 'Please select district.'
					}
				}
			},
		},
		plugins: {
			trigger: new FormValidation.plugins.Trigger(),
			bootstrap3: new FormValidation.plugins.Bootstrap3(),
			submitButton: new FormValidation.plugins.SubmitButton(),
			defaultSubmit: new FormValidation.plugins.DefaultSubmit(),
		},
	}).on('core.element.validated', function (e) {
		if (e.valid) {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-invalid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-valid');
		} else {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-valid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-invalid');
		}
	});
	$('form select').chosen().change(function () {
		fv.revalidateField($(this).attr('name'));
	});
	$("tr[data-href]").each(function(){ 
		if($(this).attr('data-href')!='#'){
			$(this).css('cursor','pointer');
			$(this).bind('click',function() {
				window.document.location = $(this).attr("data-href");
			});
		}
	});
	$('#dataTables').DataTable();
});
</script>