<?php
/**
 * 
 *  Academic/MasterController/editsectionsAction
 * 
 */
$this->headTitle($this->title);
 foreach($family as $fam):
	// print_r($fam);
 endforeach;
?>
<form id="#form" role="form" data-toggle="validator" action="<?php echo $this->url('monk', array('action' => 'editfamily','id'=>$fam['id'])); ?>" enctype="multipart/form-data" method="post" >
<div class="modal-header">
        <h5 class="modal-title"><i class="ace-icon fa fa-plus-square-o"></i> <?php echo $this->title;?></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>  <!-- /modal-header -->
    <div class="modal-body">
    	<div class="panel panel-default">
    		<div class="panel-body">
				<div class="form-group">
				<label for="monk_id" class="control-label">Monk Id</label>
					<input type="text" name="monk_id" id="monk_id" class="form-control" value="<?php echo $fam['monk_id']?>" placeholder="Monk ID" required/>
				</div>
				<div class="form-group">
					<label for="cid" class="control-label">CID</label>
					<input type="text" name="cid" id="cid" class="form-control" value="<?php echo $fam['cid']?>"  placeholder="CID" required/>
				</div>
				<div class="form-group">
					<label for="name" class="control-label">Name</label>
					<input type="text" name="name" id="name" class="form-control" value="<?php echo $fam['name']?>"  placeholder="Name" required/>
				</div>
				<div class="form-group">
					<label for="relation" class="control-label">Relation</label>
					<input type="text" name="relation" id="relation" class="form-control" value="<?php echo $fam['relation']?>"  placeholder="relation" required/>
				</div>
				<div class="form-group">
					<label for="occupation" class="control-label">Occupation</label>
					<input type="text" name="occupation" id="occupation" class="form-control" value="<?php echo $fam['occupation']?>"  placeholder="occupation" required/>
				</div>
				<div class="form-group">
					<label for="contact" class="control-label">Contact Number</label>
					<input type="text" name="contact" id="contact" class="form-control" value="<?php echo $fam['contact']?>"  placeholder="relation" required/>
				</div>
				
			</div><!-- panel-body -->
		</div><!-- panel panel-default -->	
    </div> <!-- /modal-body -->
    <div class="modal-footer">
        <button type="submit" class="btn btn-success"><i class="fa fa-check"></i> Save </button>
        <button type="reset" class="btn btn-warning" data-dismiss="modal"><i class="fa fa-times"></i> Cancel </button>        
    </div>  
</form>
<script>
$('document').ready(function(){
	const fv = FormValidation.formValidation(document.getElementById('#form'), {
		fields: {
			name: {
				validators: {
					notEmpty: {
						message: 'Please provide name.'
					}
				}
			},
			cid: {
				validators: {
					notEmpty: {
						message: 'Please provide cid.'
					}
				}
			},
		},
		plugins: {
			trigger: new FormValidation.plugins.Trigger(),
			bootstrap3: new FormValidation.plugins.Bootstrap3(),
			submitButton: new FormValidation.plugins.SubmitButton(),
			defaultSubmit: new FormValidation.plugins.DefaultSubmit(),
		},
	}).on('core.element.validated', function (e) {
		if (e.valid) {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-invalid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-valid');
		} else {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-valid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-invalid');
		}
	});

});
</script>
