<?php
/**
 * 
 * View -- of Academic/MonkController/viewqualificationAction
 * 
 */
    $this->headTitle($this->title);
?>

<?php 
     foreach ($monk as $monk):
            extract($monk);
     endforeach;        
?>
<?php echo $this->tabs_helper(array(2811,2844,2845),$id); ?>
<div class="card">
	<div class="card-header">
		<div class="btn-group pull-right">
			<?php echo $this->button(2,$id);?>
		</div>
	</div>
	<div class="table-responsive">
		<div class="table-header col-lg-6 bgc-primary text-white pt-2 pb-2"> Qualification Detail's of <?php echo $full_name?></div>
		<table id="datatable" class="d-style w-100 table text-dark-m1 text-95 border-y-1 brc-black-tp11 collapsed dtr-table">
                  <!-- add `collapsed` by default ... it will be removed by default -->
                  <!-- thead with .sticky-nav -->
         <thead class="sticky-nav text-primary-d1 text-uppercase text-100">
				<tr>
					<th>#</th>
					<th>Course</th>
					<th>Organization</th>
					<th>City/Dzongkhag</th>
					<th>Country</th>
					<?php if($this->button(1)!=""):?>
						<th class="no-print">Action</th>
					<?php endif; ?>
				</tr>
			</thead>
			<tbody>
				<?php $i=1+(($page-1)*20); foreach ($paginator as $rows):?>
				
					<tr>
						<td><?php echo $i++ ?> </td>
						<td><?php echo $rows['course']; ?></td>
						<td><?php echo $rows['organization']; ?></td>
						<td><?php echo $rows['location']; ?></td>
						<td><?php echo $rows['country']; ?></td>
						<?php if($this->button(1)!=""):?>
						<td><?php echo $this->button(1,$rows['id']);?></td>
					<?php endif;?>
				<?php 
				endforeach;  
				?>
			</tbody>
		</table>
	</div>
</div>
<!--for modal -->
<div id="modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content"> </div>
    </div>
</div>
<script>
$('document').ready(function(){
	$('#dataTables').DataTable({"paging":   true,});
});
</script>
