<?php
/**
 * 
 *  Academic/MasterController/editclassAction
 * 
 */
$this->headTitle($this->title);
 foreach($program as $cls);
 //print_r($cls);exit;
?>
<form id="#form" role="form" data-toggle="validator" action="<?php echo $this->url('masteraca', array('action' => 'addsubject','id'=>$cls['id'])); ?>" enctype="multipart/form-data" method="post" >
<div class="modal-header">
        <h5 class="modal-title"><i class="ace-icon fa fa-plus-square-o"></i> <?php echo $this->title;?></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>  <!-- /modal-header -->
    <div class="modal-body">
    	<div class="panel panel-default">
    		<div class="panel-body">	
				<div class="form-group">
					<label for="subject" class="control-label">Subject</label>
					<select class="form-control" id="subject" name="subject" data-placeholder="Select">
						<option value=""></option>
						<?php 
						foreach ($course as $row):
						?>
							<option value="<?php echo $row['name'];?>" >
								<?php echo $row['name'];?>
							</option>
						<?php
						endforeach;
						?>
					</select>
					<a data-toggle="normal" href="<?php echo $this->url('masteraca', array('action'=>'coursecatalog',));?>">
									<i class="ace-icon fa fa-plus-circle "></i>Add Course
								</a> 
				</div>
			</div><!-- panel-body -->
		</div><!-- panel panel-default -->	
    </div> <!-- /modal-body -->
    <div class="modal-footer">
        <button type="submit" class="btn btn-success"><i class="fa fa-check"></i> Save </button>
        <button type="reset" class="btn btn-warning" data-dismiss="modal"><i class="fa fa-times"></i> Cancel </button>        
    </div>  
</form>
<script>
$('document').ready(function(){
	const fv = FormValidation.formValidation(document.getElementById('#form'), {
		fields: {
			standard: {
				validators: {
					notEmpty: {
						message: 'Please provide Standard.'
					}
				}
			},
			subject: {
				validators: {
					notEmpty: {
						message: 'Please provide subject.'
					}
				}
			},
		},
		plugins: {
			trigger: new FormValidation.plugins.Trigger(),
			bootstrap3: new FormValidation.plugins.Bootstrap3(),
			submitButton: new FormValidation.plugins.SubmitButton(),
			defaultSubmit: new FormValidation.plugins.DefaultSubmit(),
		},
	}).on('core.element.validated', function (e) {
		if (e.valid) {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-invalid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-valid');
		} else {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-valid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-invalid');
		}
	});

});
</script>
