<?php
/**
 * 
 *  Academic/MasterController/editsectionsAction
 * 
 */
$this->headTitle($this->title);
 foreach($subject as $subjects):
 endforeach;
?>
<form id="#form" role="form" data-toggle="validator" action="<?php echo $this->url('masteraca', array('action' => 'editsubject','id'=>$subjects['id'])); ?>" enctype="multipart/form-data" method="post" >
<div class="modal-header">
        <h5 class="modal-title"><i class="ace-icon fa fa-plus-square-o"></i> <?php echo $this->title;?></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>  <!-- /modal-header -->
    <div class="modal-body">
    	<div class="panel panel-default">
    		<div class="panel-body">
				<!--<div class="form-group">
				<label for="standard" class="control-label">Standard</label>
					<input type="text" name="standard" id="standard" class="form-control" value="<?php echo $subjects['standard']?>" placeholder="standard" required/>
				</div> !-->
				<div class="form-group">
					<label for="subject" class="control-label">Subject</label>
					<input type="text" name="subject" id="subject" class="form-control" value="<?php echo $subjects['subject']?>"  placeholder="Section" required/>
				</div>
			</div><!-- panel-body -->
		</div><!-- panel panel-default -->	
    </div> <!-- /modal-body -->
    <div class="modal-footer">
        <button type="submit" class="btn btn-success"><i class="fa fa-check"></i> Save </button>
        <button type="reset" class="btn btn-warning" data-dismiss="modal"><i class="fa fa-times"></i> Cancel </button>        
    </div>  
</form>
<script>
$('document').ready(function(){
	const fv = FormValidation.formValidation(document.getElementById('#form'), {
		fields: {
			subject: {
				validators: {
					notEmpty: {
						message: 'Please provide Subject.'
					}
				}
			},
			classes: {
				validators: {
					notEmpty: {
						message: 'Please provide class.'
					}
				}
			},
		},
		plugins: {
			trigger: new FormValidation.plugins.Trigger(),
			bootstrap3: new FormValidation.plugins.Bootstrap3(),
			submitButton: new FormValidation.plugins.SubmitButton(),
			defaultSubmit: new FormValidation.plugins.DefaultSubmit(),
		},
	}).on('core.element.validated', function (e) {
		if (e.valid) {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-invalid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-valid');
		} else {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-valid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-invalid');
		}
	});

});
</script>
