<?php
/**
 * 
 *  Academic/MasterController/editclassAction
 * 
 */
$this->headTitle($this->title);
 foreach($courses as $course);
?>
<form id="#form" role="form" data-toggle="validator" action="<?php echo $this->url('masteraca', array('action' => 'editcoursecatalog','id'=>$course['id'])); ?>" enctype="multipart/form-data" method="post" >
<div class="modal-header">
        <h5 class="modal-title"><i class="ace-icon fa fa-plus-square-o"></i> <?php echo $this->title;?></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>  <!-- /modal-header -->
    <div class="modal-body">
    	<div class="panel panel-default">
    		<div class="panel-body">
			    <div class="form-group">
			        <label for="name" class="control-label">Course Name</label>
					<input class="form-control" id="name" value="<?php echo $course['name']?>"name="name" placeholder="Course Nmae">
					
				</div>
				<div class="form-group">
					<label for="code" class="control-label">Code</label>
					<input class="form-control" id="code" name="code" value="<?php echo $course['code'];?>" placeholder="Code">
				</div>
				<div class="form-group">
					<label for="level" class="control-label">Level</label>
					<select class="form-control" id="level" name="level" data-placeholder="Select">
					<option value="-1">None</option>
						<?php 
						foreach ($level as $row):
						 $selected = ($course['level'] == $row['id'])? "selected":"";
						?>
							<option value="<?php echo $row['id'];?>" <?php echo $selected;?>>
								<?php echo $row['standard'];?>
							</option>
						<?php
						endforeach;
						?>
					</select>
				</div>
			</div><!-- panel-body -->
		</div><!-- panel panel-default -->	
    </div> <!-- /modal-body -->
    <div class="modal-footer">
        <button type="submit" class="btn btn-success"><i class="fa fa-check"></i> Save </button>
        <button type="reset" class="btn btn-warning" data-dismiss="modal"><i class="fa fa-times"></i> Cancel </button>        
    </div>  
</form>
<script>
$('document').ready(function(){
	const fv = FormValidation.formValidation(document.getElementById('#form'), {
		fields: {
			organization: {
				validators: {
					notEmpty: {
						message: 'Please provide Organization.'
					}
				}
			},
			classes: {
				validators: {
					notEmpty: {
						message: 'Please provide class.'
					}
				}
			},
		},
		plugins: {
			trigger: new FormValidation.plugins.Trigger(),
			bootstrap3: new FormValidation.plugins.Bootstrap3(),
			submitButton: new FormValidation.plugins.SubmitButton(),
			defaultSubmit: new FormValidation.plugins.DefaultSubmit(),
		},
	}).on('core.element.validated', function (e) {
		if (e.valid) {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-invalid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-valid');
		} else {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-valid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-invalid');
		}
	});

});
</script>
