<?php
/**
 * 
 * View -- of Accounts/DemographyController/addcurrencyAction
 * 
 */
$this->headTitle($this->title);
?>
<form id="#form" method="post" action="<?php echo $this->url('fac', array('action' => 'addwash')); ?>"  enctype="multipart/form-data" >                 
<div class="modal-header">
        <h5 class="modal-title"><i class="ace-icon fa fa-plus-square-o"></i> <?php echo $this->title;?></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>  <!-- /modal-header -->
    <div class="modal-body">
		<div class="panel panel-default">
			<div class="panel-body">
		    	<div class="form-group">
					<label for="location" class="control-label">Location</label>
					<select class="form-control" id="location" name="location" data-placeholder="Select" required >
						<option value=""></option>
						<?php 
						foreach ($locations as $loc):
						?>
							<option value="<?php echo $loc['id'];?>">
								<?php echo $loc['location'];?>
							</option>
						<?php
						endforeach;
						?>
					</select>
				</div>   
				<div class="form-group">
					<label for="organization" class="control-label">Organization</label>
					<select class="form-control chosen-widget" id="organization" name="organization" data-placeholder="Select" required >
						<option value=""></option>
					</select>
				</div>    
			    <div class="form-group">
				    <label for="btn" class="control-label">Water</label>
					<div class="checkbox">
						<label>
							<input class="ace" type="checkbox" name="water" id="water" value="1"/>
							<span class="lbl"> Is there enough water supply? </span>
						</label>
						<label>
							<input class="ace" type="checkbox" name="water1" id="water1" value="1" />
							<span class="lbl"> Is safe drinking water available? </span>
						</label>
					</div>
				</div>
				<div class="form-group">
				    <label for="btn" class="control-label">Sanitation</label>
					<div class="radio">
						<label>
							<input class="ace" type="checkbox" name="sanitation" id="sanitation" value="1"  />
							<span class="lbl"> Is there proper waste Disposal?</span>
						</label>
						<label>
							<input class="ace" type="checkbox" name="sanitation1" id="sanitation1" value="1"  />
							<span class="lbl"> Is there proper Toilet facilities? </span>
						</label>
					</div>
				</div>
				<div class="form-group">
				    <label for="btn" class="control-label ">Hygiene</label>
					<div class="radio">
						<label>
							<input class="ace" type="checkbox" name="hygiene" id="hygiene" value="1"  />
							<span class="lbl"> Is there bathing and handwashing facility? </span>
						</label>
						<label>
							<input class="ace" type="checkbox" name="hygiene1" id="hygiene1" value="1" />
							<span class="lbl">Is there availablity for menstrual hygiene management?</span>
						</label>
					</div>
				</div>
			</div>
		</div>                    
    </div><!-- /modal-body -->
    <div class="modal-footer">
        <button type="submit" class="btn btn-success"><i class="fa fa-check"></i> Save </button>
        <button type="button" class="btn btn-warning" data-dismiss="modal" ><i class="fa fa-times"></i> Cancel </button> 
    </div><!-- /modal-footer -->
</form>
<script>
$(function(){
	$('#location').on('change', function(){
			//alert($(this).val());
		$.post(
			"<?php echo $this->url('fac', array('action' => 'getorganization')); ?>",
			{
				location_id: $(this).val(),
			},
			function(data){
				//console.log(data);
				$("#organization").html(data.org);
				$("#organization").trigger('chosen:updated');				
			},
			'json'
		);	
	});
	const fv = FormValidation.formValidation(document.getElementById('#form'), {
		fields: {
			income: {
				validators: {
					notEmpty: {
						message: 'Please select Income.'
					}
				}
			},
			expense: {
				validators: {
					notEmpty: {
						message: 'Please select Expense.'
					}
				}
			},
		},
		plugins: {
			trigger: new FormValidation.plugins.Trigger(),
			bootstrap3: new FormValidation.plugins.Bootstrap3(),
			submitButton: new FormValidation.plugins.SubmitButton(),
			defaultSubmit: new FormValidation.plugins.DefaultSubmit(),
		},
	}).on('core.element.validated', function (e) {
		if (e.valid) {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-invalid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-valid');
		} else {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-valid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-invalid');
		}
	});
	$('form select').chosen().change(function () {
		fv.revalidateField($(this).attr('name'));
	});
});
</script>