<?php
/**
 * 
 * View -- of Accounts/DemographyController/editcurrencyAction
 * 
 */
$this->headTitle($this->title);
//echo '<pre>';print_r($currencies);exit;
foreach($organizations as $or):
	//echo"<pre>"; print_r($eq); exit; 
    extract($or);
endforeach;
foreach($washs as $f):
	//echo"<pre>"; print_r($eq); exit; 
    extract($f);
endforeach;
?>
<?php foreach($wash as $row);?>                      
<form method="post" action="<?php echo $this->url('fac', array('action' => 'editwash', 'id' => $row['id'])); ?>"  enctype="multipart/form-data" >                 
<div class="modal-header">
        <h5 class="modal-title"><i class="ace-icon fa fa-plus-square-o"></i> <?php echo $this->title;?></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>  <!-- /modal-header -->
	<div class="modal-body">
		<div class="panel panel-default">
			<div class="panel-body"> 
			    <div class="form-group">
					<label for="location" class="control-label">Location</label>
					<select class="form-control" id="location" name="location" data-placeholder="Select" required >
						<option value=""></option>
						<?php 
						foreach ($locations as $loc):
							$selected=($location==$loc['id'])?"selected":"";
						?>
							<option value="<?php echo $loc['id'];?>"<?php echo $selected;?>>
								<?php echo $loc['location'];?>
							</option>
						<?php
						endforeach;
						?>
					</select>
				</div>
				<div class="form-group">
					<label for="location" class="control-label">Organization</label>
					<select class="form-control chosen-widget" id="organization" name="organization" data-placeholder="Select" required >
						<option value=""></option>
						<?php 
						foreach ($this->organizationObj->get(array('location'=>$location)) as $orgs):
							$selected=($organization==$orgs['id'])?"selected":"";
						?>
							<option value="<?php echo $orgs['id'];?>"<?php echo $selected;?>>
								<?php echo $orgs['department'];?>
							</option>
						<?php
						endforeach;
						?>
					</select>
				</div>        
				<div class="form-group">
				<input type="hidden" id="wash_id" name="wash_id" value="<?php echo $row['id'];?>" />
					<label for="btn" class="control-label">Water</label>
					<div class="checkbox">
						<label>
							<input class="ace" type="checkbox" name="water" id="water" value="1"<?php echo ($row['water_facility']=='1')?"checked":"";?>/>
							<span class="lbl"> Is there enough water supply? </span>
						</label>
						<label>
							<input class="ace" type="checkbox" name="water1" id="water1" value="1" <?php echo ($row['water_facility1']=='1')?"checked":"";?>/>
							<span class="lbl"> Is safe drinking water available? </span>
						</label>
					</div>
				</div>
				<div class="form-group">
					<label for="btn" class="control-label">Sanitation</label>
					<div class="radio">
						<label>
							<input class="ace" type="checkbox" name="sanitation" id="sanitation" value="1" <?php echo ($row['sanitation_facility']=='1')?"checked":"";?> />
							<span class="lbl"> Is there proper waste Disposal?</span>
						</label>
						<label>
							<input class="ace" type="checkbox" name="sanitation1" id="sanitation1" value="1"<?php echo ($row['sanitation_facility']=='1')?"checked":"";?>  />
							<span class="lbl"> Is there proper Toilet facilities? </span>
						</label>
					</div>
				</div>
				<div class="form-group">
					<label for="btn" class="control-label ">Hygiene</label>
					<div class="radio">
						<label>
							<input class="ace" type="checkbox" name="hygiene" id="hygiene" value="1" <?php echo ($row['hygiene_facility']=='1')?"checked":"";?> />
							<span class="lbl"> Is there bathing and handwashing facility? </span>
						</label>
						<label>
							<input class="ace" type="checkbox" name="hygiene1" id="hygiene1" value="1" <?php echo ($row['hygiene_facility1']=='1')?"checked":"";?>/>
							<span class="lbl">Is there availablity for menstrual hygiene management?</span>
						</label>
					</div>
				</div>
		    </div>
	    </div>
    </div>       
    <div class="modal-footer">
        <button type="submit" class="btn btn-success"><i class="fa fa-check"></i> Save </button>
        <button type="button" class="btn btn-warning" data-dismiss="modal" ><i class="fa fa-times"></i> Cancel </button> 
    </div><!-- /modal-footer -->
</form>
<script>
$('document').ready(function(){
	$('#location').on('change', function(){
		//alert($(this).val());
		$.post(
			"<?php echo $this->url('fac', array('action' => 'getorganization')); ?>",
			{
				location_id: $(this).val(),
			},
			function(data){
				//console.log(data);
				$("#organization").html(data.org);
				$("#organization").trigger('chosen:updated');				
			},
			'json'
		);	
	});
	$('select').chosen({ allow_single_deselect: true });		
	$('document').ready(function(){
		const fv = FormValidation.formValidation(document.getElementById('#form'), {
			fields: {
				fur: {
					validators: {
						notEmpty: {
							message: 'Please provide Furniture.'
						}
					}
				},
			},
		plugins: {
			trigger: new FormValidation.plugins.Trigger(),
			bootstrap3: new FormValidation.plugins.Bootstrap3(),
			submitButton: new FormValidation.plugins.SubmitButton(),
			defaultSubmit: new FormValidation.plugins.DefaultSubmit(),
		},
	}).on('core.element.validated', function (e) {
		if (e.valid) {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-invalid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-valid');
		} else {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-valid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-invalid');
		}
	});
	$('form select').chosen().change(function () {
		fv.revalidateField($(this).attr('name'));
	});
	});
});
</script>

                                

      
