<?php
/**
 *  pay head report---Hr/ReportController/htpitreport  
 */
	$this->headTitle($this->title);
?>
<?php echo $this->partial('hr/payroll-report/partial.phtml', array('active' => 'htpitreport')); ?><br/>
<?php	
	$earningHead = $this->payheadObj->get(array('deduction'=>0));
	$earning=ceil(count($earningHead)); //no of earning columns
	$earning = $earning - 1;
?>
<div class="widget widget-box transparent">
	<div class="widget-header">
		<h4 class="widget-title"> 	
			Health Tax & Personal Income Tax Report
		</h4>
		<div class="pull-right tableTools-container"></div>
	</div>	
	<div class="widget-body">
		<div class="widget-main">
			<form >
				<div class="row">
					<div class="col-md-2">
						<label for="month" class="control-label">Month </label>
						<select class="form-control" name="month" id="month" data-placeholder="Select" required >
							<option value=""></option>
							<?php 
								for($m=1;$m<=12;$m++):
									$selected = ($data['month'] == $m)?'selected':'';
							?>
								<option value="<?php echo $m;?>" <?php echo $selected;?>>
									<?php echo date("F", strtotime(date("d-$m-y"))); ?>
								</option>
							<?php endfor; ?>
						</select>
					</div>
					<div class="col-md-2">
						<label for="year" class="control-label">Year </label>
						<select class="form-control" name="year" id="year" data-placeholder="Select" required >
							<option value=""></option>
							<?php $minYear = $this->payrollObj->getMin('year');
$minYear = ($this->minYear > 0)?$this->minYear:date('Y');?>
							<?php for($y=date('Y');$y >= $minYear; $y--):
								$selected = ($data['year'] == $y)?'selected':'';?>
								<option value="<?php echo $y;?>" <?php echo $selected;?>>
									<?php echo $y; ?>
								</option>
							<?php endfor; ?>
						</select>
					</div>
					<div class="col-md-2">
						<label for="region" class="control-label">Region</label>
						<select class="form-control" id="region" name="region" data-placeholder="Select"  required >
							<option value="-1">All</option>
							<?php 
							foreach ($regions as $region):
							?>
							<?php $selected = ($region['id'] == $data['region'])?'selected':'';?>
								<option value="<?php echo $region['id'];?>" <?php echo $selected;?>>
									<?php echo $region['region'];?>
								</option>
							<?php
							endforeach;
							?>
						</select>
					</div>
					<div class="col-md-2">
						<label for="location" class="control-label">Location</label>
						<select class="form-control" id="location" name="location" data-placeholder="Select" required >
							<option value="-1">All</option>
							<?php 
							foreach ($location as $location):
							?>
								<?php $selected = ($location['id'] == $data['location'])?'selected':'';?>
								<option value="<?php echo $location['id'];?>" <?php echo $selected;?>>
									<?php echo $location['location'];?>
								</option>
							<?php
							endforeach;
							?>
						</select>
					</div>
					<div class="col-md-4">
						<div class="space-10"></div>
						<label for="redirect" class="control-label">&nbsp;</label>
						<button type="button" class="btn btn-sm btn-success" onclick="redirect();"><i class="fa fa-refresh"></i> refresh </button>
					</div>
				</div>
			</form>
			<div class="row"><div class="space-12"></div></div>
			<div class="row">
				<div class="col-lg-12">
					<strong>For the Month of : <?php $month = $data['month']; echo date("F", strtotime(date("d-$month-y"))); ?>, <?php echo $data['year']; ?>
					<?php
						$filter = array(
							'year'=>$data['year'], 
							'month'=>$data['month'], 
							'pr.status'=>'1'									
						);
						if($data['region'] > 0):
							$filter['l.region'] = $data['region']; 
						endif;
						if($data['location'] > 0):
							$filter['e.location'] = $data['location']; 
						endif;
						$payrolls = $this->payrollObj->getforReport($filter);
						if(sizeof($payrolls) > 0):
							//Payroll Generated
						else:
							$temp_payrolls = $this->temppayrollObj->getforReport($filter);
							if(sizeof($temp_payrolls) > 0)://Draft?>
					<span class="label label-danger">DRAFT</span>
					<?php	else: //Not Generated ?>
								<span class="label label-warning"><i class="fa fa-exclamation-triangle"></i> NOT PREPARED</span>
					<?php	endif;
						endif;
					?>
					</strong>
					<span class="pull-right"> Date:  <?php echo date('d/m/Y');?></span>
				</div>
			</div>	
			<div class="space-6"></div>
			<div class="row">	
			<table class="table-condensed table-striped table-bordered table-hover" id="reportTable">
				<thead>
					<tr>
						<th rowspan="2">#</th>
						<th rowspan="2">NAME OF EMPLOYEE</th>
						<th rowspan="2">CID NO.</th>
						<th rowspan="2">TAX PAYER NO.</th>
						<th rowspan="2">BASIC SALARY</th>
						<th colspan="<?php echo $earning;?>" style="text-align:center">BENIFITS/ALLOWANCES</th>
						<th rowspan="2">GROSS SALARY</th>
						<th rowspan="2">SALARY TAX</th>
						<th rowspan="2">HEALTH CONTRIB.</th>
						<th rowspan="2">TOTAL TAX</th>
					</tr>
					<tr>
						<!-- Earnings columns -->
						<?php foreach($earningHead as $key => $row):
								if($row['id'] != 1):?>
								<th><?php echo $row['code'];?></th>
						<?php endif;
							endforeach;?> 
					</tr>
				</thead>
				<tbody>
					<?php $i = 1; 
					$filter = array(
							'year'=>$data['year'], 
							'month'=>$data['month'], 
							'pr.status'=>'1'									
					);
					if($data['region'] > 0):
						$filter['l.region'] = $data['region']; 
					endif;
					if($data['location'] > 0):
						$filter['e.location'] = $data['location']; 
					endif;
					$tot_earning = array();
					$tot_deduction = array();
					$tot_basic_salary = 0;
					$tot_gross_salary = 0;
					$tot_salary_tax = 0;
					$tot_health_tax = 0;
					$tot_total_tax = 0;
					$pay_rolls = $this->payrollObj->getforReport($filter);
					if(sizeof($pay_rolls) > 0):
					foreach ($pay_rolls as $pay_roll):?>
						<tr>
							<td><?php echo $i++; ?> </td>
							<td><?php echo $pay_roll['full_name']; ?></td>
							<td><?php echo $pay_roll['cid']; ?></td>
							<td><?php 
								$pit_tax_no = $this->paydetailObj->getColumn(array('pay_roll' => $pay_roll['id'], 'pay_head' => '11'), 'ref_no');
								if($pit_tax_no == ''):
									echo $ht_tax_no = $this->paydetailObj->getColumn(array('pay_roll' => $pay_roll['id'], 'pay_head' => '16'), 'ref_no');
								else:
									echo $pit_tax_no;
								endif;
							?></td>
							<td><?php 
								$basic_salary = $this->paydetailObj->getColumn(array('pay_roll' => $pay_roll['id'], 'pay_head' => '1'), 'amount');
								echo $this->decimal($basic_salary);
								$tot_basic_salary +=$basic_salary;
							?></td>
							<!-- values for earning column -->
							<?php foreach ($earningHead as $key => $row): if($row['id'] != 1):?>
								<td><?php
									$amount = (int)$this->paydetailObj->getColumn(array('pay_roll' => $pay_roll['id'], 'pay_head' => $row['id']), 'amount');
									echo $this->decimal($amount);
									$tot_earning[$key] += $amount;
								?></td>
							<?php endif; endforeach;?>
							<td>
							<?php
								$gross_salary = (int)$this->payrollObj->getColumn(array('employee' => $pay_roll['employee_id'], 'year' => $data['year'], 'month' => $data['month']), 'gross');
								echo $this->decimal($gross_salary);
								$tot_gross_salary +=$gross_salary;
							?></td>
							<td><?php 
								$salary_tax = $this->paydetailObj->getColumn(array('pay_roll' => $pay_roll['id'], 'pay_head' => '11'), 'amount');
								echo $this->decimal($salary_tax);
								$tot_salary_tax +=$salary_tax;
							?></td>
							 <td><?php 
								$health_tax = $this->paydetailObj->getColumn(array('pay_roll' => $pay_roll['id'], 'pay_head' => '16'), 'amount');
								echo $this->decimal($health_tax);
								$tot_health_tax +=$health_tax;
							?></td>
							 <td><?php 
								$total_tax = $salary_tax + $health_tax;
								echo $this->decimal($total_tax);
								$tot_total_tax +=$total_tax;
							?></td>
						<tr>
					<?php endforeach;
					else:
					$temp_payrolls = $this->temppayrollObj->getforReport($filter);
					foreach($temp_payrolls as $temp_payroll):
					?>
						<tr>
							<td><?php echo $i++; ?> </td>
							<td><?php echo $temp_payroll['full_name']; ?></td>
							<td><?php echo $temp_payroll['cid']; ?></td>
							<td><?php 
								$pit_tax_no = $this->paystructureObj->getColumn(array('employee' => $temp_payroll['employee_id'], 'pay_head' => '11'), 'ref_no');
								if($pit_tax_no == ''):
									echo $ht_tax_no = $this->paystructureObj->getColumn(array('employee' => $temp_payroll['employee_id'], 'pay_head' => '16'), 'ref_no');
								else:
									echo $pit_tax_no;
								endif;
							?></td>
							<td><?php 
								$basic_salary = $this->paystructureObj->getColumn(array('employee' => $temp_payroll['employee_id'], 'pay_head' => '1'), 'amount');
								echo $this->decimal($basic_salary);
								$tot_basic_salary +=$basic_salary;
							?></td>
							<!-- values for earning column -->
							<?php foreach ($earningHead as $key => $row): if($row['id'] != 1):?>
								<td><?php
									$amount = (int)$this->paystructureObj->getColumn(array('employee' => $temp_payroll['employee_id'], 'pay_head' => $row['id']), 'amount');
									echo $this->decimal($amount);
									$tot_earning[$key] += $amount;
								?></td>
							<?php endif; endforeach;?>
							<td>
							<?php
								$gross_salary = (int)$this->temppayrollObj->getColumn(array('employee' => $temp_payroll['employee_id'], 'year' => $data['year'], 'month' => $data['month']), 'gross');
								echo $this->decimal($gross_salary);
								$tot_gross_salary +=$gross_salary;
							?></td>
							<td><?php 
								$salary_tax = $this->paystructureObj->getColumn(array('employee' => $temp_payroll['employee_id'], 'pay_head' => '11'), 'amount');
								echo $this->decimal($salary_tax);
								$tot_salary_tax +=$salary_tax;
							?></td>
							 <td><?php 
								$health_tax = $this->paystructureObj->getColumn(array('employee' => $temp_payroll['employee_id'], 'pay_head' => '16'), 'amount');
								echo $this->decimal($health_tax);
								$tot_health_tax +=$health_tax;
							?></td>
							 <td><?php 
								$total_tax = $salary_tax + $health_tax;
								echo $this->decimal($total_tax);
								$tot_total_tax +=$total_tax;
							?></td>
						<tr>
					<?php endforeach;
					endif;?>
					<tr>
						<td colspan="4" style="text-align:right"> <strong>Total:   </strong></td>
						<td><strong><?php echo $this->decimal($tot_basic_salary);?></strong></td>
						<!-- values for earning column -->
						<?php foreach($earningHead as $key => $row): if($row['id'] != 1):?>
							<td><strong><?php echo $this->decimal($tot_earning[$key]); ?></strong></td>
						<?php endif; endforeach;?>
						<td><strong><?php echo $this->decimal($tot_gross_salary);?></strong></td>
						<td><strong><?php echo $this->decimal($tot_salary_tax);?></strong></td>
						<td><strong><?php echo $this->decimal($tot_health_tax);?></strong></td>
						<td><strong><?php echo $this->decimal($tot_total_tax);?></strong></td>
					</tr>	
				</tbody>
			</table>
			</div>

			<div class="space-12"></div>
			<div class="row">
				<div class="col-lg-8"></div>
				<div class="col-lg-2">SIGNITURE OF DISBURSING OFFICER</div>
			</div>
		</div>
	</div>
</div>
<!--for modal -->
<div id="modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content"> </div>
    </div>
</div>
<script type="text/javascript">
	$('#reportTable').genpdftable({
		src:"<?php echo $this->url('pdfxls', array('action' => 'pdf'));?>",
		orentation:"L",//L =landscape, P = potrait
		caller:"#print"
	});
	$("#region").change(function() { 
		$.post( "<?php echo $this->url('ajresponse', array('action' => 'getlocation')); ?>/"+ $("#region").val(), function( data ) {
			var newdata ="<option value='-1'>All</option>"+data;
			$('#location').html( newdata );
			$("#location").trigger('chosen:updated');
		});
	});
	$('form select').chosen({ allow_single_deselect: true });
	function redirect(){
		var id = $('#region').val()+'&'+$('#location').val()+'&'+$('#year').val()+'&'+$('#month').val();
		location.href="<?php echo $this->url('preport', array('action'=>'htpitreport'));?>/"+id;
	}
</script>
