<?php
/**
 *  pay head report---Hr/ReportController/loanreportAction  
 */
	$this->headTitle($this->title);
?>
<?php echo $this->partial('hr/payroll-report/partial.phtml', array('active' => 'loanreport')); ?><br/>
<?php
	extract($this->data);
?>
<div class="widget widget-box transparent">
	<div class="widget-header">
		<h4 class="widget-title"> 	
			Pay Head Report
		</h4>
		<div class="pull-right tableTools-container"></div>
	</div>
	<div class="widget-body">
		<div class="widget-main">
			<div class="row"><div class="space-12"></div></div>
			<form>
				<div class="row">
					<div class="col-md-3">
						<label for="month" class="control-label">Month </label>
						<select class="form-control" name="month" id="month" data-placeholder="Select" required >
							<option value=""></option>
							<?php 
								for($m=1;$m<=12;$m++):
									$selected = ($month == $m)?'selected':'';
							?>
								<option value="<?php echo $m;?>" <?php echo $selected;?>>
									<?php echo date("F", strtotime(date("d-$m-y"))); ?>
								</option>
							<?php endfor; ?>
						</select>
					</div>
					<div class="col-md-3">
						<label for="year" class="control-label">Year </label>
						<select class="form-control" name="year" id="year" data-placeholder="Select" required >
							<option value=""></option>
							<?php $minYear = $this->payrollObj->getMin('year');
$minYear = ($this->minYear > 0)?$this->minYear:date('Y');?>
							<?php for($y=date('Y');$y >= $minYear;$y--):
								$selected = ($year == $y)?'selected':'';?>
								<option value="<?php echo $y;?>" <?php echo $selected;?>>
									<?php echo $y; ?>
								</option>
							<?php endfor; ?>
						</select>
					</div>
					<div class="col-md-3">
						<label for="region" class="control-label">Region</label>
						<select class="form-control" id="region" name="region" data-placeholder="Select"  required >
							<option value="-1">All</option>
							<?php 
							foreach ($regions as $region):
							?>
							<?php $selected = ($region['id'] == $data_region)?'selected':'';?>
								<option value="<?php echo $region['id'];?>" <?php echo $selected;?>>
									<?php echo $region['region'];?>
								</option>
							<?php
							endforeach;
							?>
						</select>
					</div>
					<div class="col-md-3">
						<label for="location" class="control-label">Location</label>
						<select class="form-control" id="location" name="location" data-placeholder="Select" required >
							<option value="-1">All</option>
							<?php 
							foreach ($location as $location):
							?>
								<?php $selected = ($location['id'] == $data_location)?'selected':'';?>
								<option value="<?php echo $location['id'];?>" <?php echo $selected;?>>
									<?php echo $location['location'];?>
								</option>
							<?php
							endforeach;
							?>
						</select>
					</div>
				</div>
				<div class="row">
					<div class="col-md-3">
						<label for="payhead" class="control-label">Pay Head Type</label>
						<select class="form-control chosen-select tag-input-style" id="payhead" name="payhead" data-placeholder="Choose a Pay Head...">
							<?php foreach($this->payheadtypeObj->getAll() as $payheadtype): 
								$selected = (in_array($payheadtype['id'], $this->payheads, true))? 'selected':'';
							?>
								<option value="<?php echo $payheadtype['id'];?>" <?php echo $selected;?> > <?php echo $payheadtype['head_type'];?> </option>
							<?php endforeach; ?>
						</select>
					</div>
					<div class="col-md-1">
						<label for="redirect" class="control-label">&nbsp;</label>
						<button type="button" class="btn btn-sm btn-success" onclick="redirect();"><i class="fa fa-refresh"></i> refresh </button>
					</div>
				</div>
			</form>
			<div class="row">
				<div class="col-lg-12" align ="center">
					<?php $size = sizeof($this->payheads); $i =1;?>
					<strong>Report On <?php foreach($payheads as $pay_head): ?>
						<?php echo $this->payheadtypeObj->getColumn($pay_head,'head_type');?> <?php if($i++ != $size):?>,<?php endif;?>
					<?php endforeach;?></strong>
				</div>
			</div>
			<div class="row">
				<div class="col-lg-12">
					<strong>For the Month of : <?php echo date("F", strtotime(date("d-$month-y"))); ?>, <?php echo $year; ?>
						<?php 
							if($data_location > 0):
								$payrolls = $this->payrollObj->getforReport(array('month'=>$month, 'year'=>$year, 'e.location'=>$data_location));
							elseif($data_region > 0):
								$payrolls = $this->payrollObj->getforReport(array('month'=>$month, 'year'=>$year, 'l.region'=> $data_region));
							else:
								$payrolls = $this->payrollObj->getforReport(array('month'=>$month, 'year'=>$year));
							endif;
							if(sizeof($payrolls) > 0):
								//Payroll Generated
							else:
								if($data_location > 0):
									$temp_payrolls = $this->temppayrollObj->getforReport(array('month'=>$month, 'year'=>$year, 'e.location'=>$data_location));
								elseif($data_region > 0):
									$temp_payrolls = $this->temppayrollObj->getforReport(array('month'=>$month, 'year'=>$year, 'l.region'=> $data_region));
								else:
									$temp_payrolls = $this->temppayrollObj->getforReport(array('month'=>$month, 'year'=>$year));
								endif;
								if(sizeof($temp_payrolls) > 0)://Draft?>
									<span class="label label-danger">DRAFT</span>
						<?php	else: //Not Generated ?>
									<span class="label label-warning"><i class="fa fa-exclamation-triangle"></i> NOT PREPARED</span>
						<?php	endif;
							endif;
						?>
					</strong>
					<span class="pull-right"> Date:  <?php echo date('d/m/Y');?></span>
				</div>
			</div>	
			<div class="space-6"></div>
			<div class="row">	
			<table class="table table-striped table-bordered" id="printTable">
				<thead>
					<tr >
						<th rowspan='2'>#</th>
						<th rowspan='2'>Name</th>
						<th rowspan='2'>Designation</th>
						<?php $pay_heads = $this->payheadObj->get(array('payhead_type'=>$payheads));
							foreach($pay_heads as $pay_head):
						?>
							<th colspan='2'><?php echo $pay_head['pay_head'];?></th>
						<?php endforeach;?>
					</tr>
					<tr >
						<?php $pay_heads = $this->payheadObj->get(array('payhead_type'=>$payheads));
							foreach($pay_heads as $pay_head):
						?>
							<th>ACC No.</th>
							<th>Amount</th>
						<?php endforeach;?>
					</tr>
				</thead>
				<tbody>
					<?php 
					$payhead_id = implode('_',$this->payheads);
					$i =1;
					$sum = array();
					if($data_location > 0):
						$payrolls = $this->payrollObj->getforReport(array('month'=>$month, 'year'=>$year, 'e.location'=>$data_location));
					elseif($data_region > 0):
						$payrolls = $this->payrollObj->getforReport(array('month'=>$month, 'year'=>$year, 'l.region'=> $data_region));
					else:
						$payrolls = $this->payrollObj->getforReport(array('month'=>$month, 'year'=>$year));
					endif;
					if(sizeof($payrolls) > 0):
					foreach($payrolls as $payroll):?>
						<?php $pay_heads = $this->payheadObj->get(array('payhead_type'=>$payheads));
							$tot_amt = 0;
							foreach($pay_heads as $pay_head):
								$tot_amt += $this->paydetailObj->getColumn(array('pay_roll'=> $payroll['id'], 'pay_head' =>$pay_head['id']),'amount');
							endforeach;
						?>
						<?php if($tot_amt > 0):?>
								<tr>
									<td><?php echo $i++;?></td>
									<td><?php echo $payroll['full_name'];?></td>
									<td><?php echo $payroll['position_title'];?></td>
									<?php $pay_heads = $this->payheadObj->get(array('payhead_type'=>$payheads));
									foreach($pay_heads as $pay_head):
										$amt = $this->paydetailObj->getColumn(array('pay_roll'=> $payroll['id'], 'pay_head' =>$pay_head['id']),'amount');
										$paydetail_id = $this->paydetailObj->getColumn(array('pay_roll'=> $payroll['id'], 'pay_head' =>$pay_head['id']),'id');
										$accno =($paydetail_id > 0 )? $this->paydetailObj->getColumn($paydetail_id,'ref_no'):'';
									?>
									<td>
										<div class="col-lg-10">
											<?php if(strlen($accno) > 0):
												echo $accno;
											else:
												$acc_no = '--'; 
												echo $acc_no;
											endif;?>
										</div>
									</td>
									<td>
										<div class="col-lg-10">
											<?php if($amt > 0):
												echo $amt;
												$sum[$pay_head['id']] += $amt;
											else:
												$namt = '--'; 
												echo $namt;
											endif;?>
										</div>
									</td>
									<?php endforeach;?>
								</tr>
						<?php endif;
						endforeach; 
					else:
						if($data_location > 0):
							$temp_payrolls = $this->temppayrollObj->getforReport(array('month'=>$month, 'year'=>$year, 'e.location'=>$data_location));
						elseif($data_region > 0):
							$temp_payrolls = $this->temppayrollObj->getforReport(array('month'=>$month, 'year'=>$year, 'l.region'=> $data_region));
						else:
							$temp_payrolls = $this->temppayrollObj->getforReport(array('month'=>$month, 'year'=>$year));
						endif;
						if(sizeof($temp_payrolls) > 0):
							foreach($temp_payrolls as $temp_payroll):
								$pay_heads = $this->payheadObj->get(array('payhead_type'=>$payheads));
								$tot_amt = 0;
								foreach($pay_heads as $pay_head):
									$tot_amt += $this->paystructureObj->getColumn(array('employee'=> $temp_payroll['employee_id'], 'pay_head' =>$pay_head['id']),'amount');
								endforeach;
								if($tot_amt > 0):
					?>
								<tr>
									<td><?php echo $i++;?></td>
									<td><?php echo $temp_payroll['full_name'];?></td>
									<td><?php echo $temp_payroll['position_title'];?></td>
									<?php $pay_heads = $this->payheadObj->get(array('payhead_type'=>$payheads));
									foreach($pay_heads as $pay_head):
										$amt = $this->paystructureObj->getColumn(array('employee'=> $temp_payroll['employee_id'], 'pay_head' =>$pay_head['id']),'amount');
										$paydetail_id = $this->paystructureObj->getColumn(array('employee'=> $temp_payroll['employee_id'], 'pay_head' =>$pay_head['id']),'id');
										$accno =($paydetail_id > 0 )? $this->paystructureObj->getColumn($paydetail_id,'ref_no'):'';
									?>
									<td>
										<div class="col-lg-10">
											<?php if(strlen($accno) > 0):
												echo $accno;
											else:
												$acc_no = '--'; 
												echo $acc_no;
											endif;?>
										</div>
									</td>
									<td>
										<div class="col-lg-10">
											<?php if($amt > 0):
												echo $amt;
												$sum[$pay_head['id']] += $amt;
											else:
												$namt = '--'; 
												echo $namt;
											endif;?>
										</div>
									</td>
									<?php endforeach;?>
								</tr>
					<?php 		endif;
							endforeach;
						endif;
					endif;?>
					<tr>
						<td colspan="3" align="right"><b>Total</b></td>
						<?php $pay_heads = $this->payheadObj->get(array('payhead_type'=>$payheads));
							foreach($pay_heads as $pay_head):
						?>
						<td></td>
						<td align="center">
							<b><?php echo $this->currency($sum[$pay_head['id']]);?></b>
						</td>
					<?php endforeach;?>
					</tr>							
				</tbody>
			</table>
			</div>

			<div class="space-12"></div>
			<div class="row">
				<div class="col-lg-8"></div>
				<div class="col-lg-2">SIGNITURE OF DISBURSING OFFICER</div>
			</div>
		</div>
	</div>
</div>
<!--for modal -->
<div id="modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content"> </div>
    </div>
</div>
<script type="text/javascript">
	$('#printTable').genpdftable({
		src:"<?php echo $this->url('pdfxls', array('action' => 'pdf'));?>",
		orentation:"P",//L =landscape, P = potrait
	});
	$("#region").change(function() { 
		$.post( "<?php echo $this->url('ajresponse', array('action' => 'getlocation')); ?>/"+ $("#region").val(), function( data ) {
			var newdata ="<option value='-1'>All</option>"+data;
			$('#location').html( newdata );
			$("#location").trigger('chosen:updated');
		});
	});
	$('form select').chosen({ allow_single_deselect: true });
	function redirect(){
		var payheads = $('#payhead').val();
		var id = $('#month').val()+'&'+$('#year').val()+'&'+payheads+'&'+$('#region').val()+'&'+$('#location').val();
		location.href="<?php echo $this->url('preport', array('action'=>'loanreport'));?>/"+id;
	}
</script>
