<?php 
/**
 * View -- of Accounts/MasterController/currencyAction
 * chophel@athang.com -- 2022
 */
	$this->headTitle($this->title);
?>
<?php echo $this->tabs_helper(array(2702,2705)); ?>
<div class="card">
    <div class="card-header">
		<div class="btn-group pull-right">
			<?php echo $this->button(2,$page);?>
		</div>
	</div>
	<div class="table-responsive">
	<table id="datatable" class="d-style w-100 table text-dark-m1 text-95 border-y-1 brc-black-tp11 collapsed dtr-table">
                  <!-- add `collapsed` by default ... it will be removed by default -->
                  <!-- thead with .sticky-nav -->
         <thead class="sticky-nav text-primary-d1 text-uppercase text-100">
				<tr>
					<th>#</th>
					<th>Organization</th>
					<th>Equipment Name</th>
					<th>Type</th>
					<th>Useable</th>
					<th>Not Usable</th>
					<?php if($this->button(1)!=""):?>
						<th class="no-sort no-printpdf">Action</th>
					<?php endif;?>	
				</tr>
			</thead>
			<tbody>
			<?php $i=1+(($page-1)*20); foreach ($paginator as $row):
				//echo '<pre>';print_r($paginator);exit;?>
				<tr>
					<td><?php  echo $i++; ?></td>		
					<td><?php echo $this->organizationObj->getColumn($row['organization'],'location');?></td>
					<td class="fw-bold"><?php echo $row['equipment_name'];?></td>
					<td><?php echo $this->equipmenttypeObj->getColumn($row['equipment_type'],'name');?></td>
					<td class="fw-bold"><?php echo $row['usable'];?></td>
					<td class="fw-bold"><?php echo $row['not_usable'];?></td>
					<?php if($this->button(1)!=""):?>
						<td><?php echo $this->button(1, $row['id'].'_'.$page);?></td>
					<?php endif;?>
				</tr>
			<?php endforeach; ?>
			</tbody>
		</table>
	</div>
</div>
<div class="modal fade" id="modal" tabindex="-1" role="dialog" aria-hidden="true">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
		</div><!-- /.modal-content -->
	</div><!-- /.modal-dialog -->
</div><!-- /.modal -->
<script>
$('document').ready(function(){
	$('#dataTables').DataTable({
		"paging":   true,
	});
});
</script>