<?php
/**
 * View -- of Administration/MasterController/adddepartment
 * chophel@athang.com
 */
$this->headTitle($this->title);
?>
<form id="#form" method="post" action="<?php echo $this->url('setmaster', array('action' => 'adddepartment','id'=>$page)); ?>" enctype="multipart/form-data">
<div class="modal-header">
        <h5 class="modal-title"><i class="ace-icon fa fa-plus-square-o"></i> <?php echo $this->title;?></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>  <!-- /modal-header -->   
    <div class="modal-body">
		<div class="panel panel-default">                       
			<div class="panel-body">   
				<div class="form-group">
					<label for="department" class="control-label">organization Name</label>
					<input type="text" class="form-control" name="department" id="department" size="30" placeholder="Department" required> 
				</div>
				<div class="form-group">
					<label for="dzongkhag" class="control-label">Dzongkhag</label>
					<select class="form-control" id="dzongkhag" name="dzongkhag" data-placeholder="Select" required >
									<option value=""></option>
									<?php 
									foreach ($dzongkhags as $dzongkhag):
									?>
										<option value="<?php echo $dzongkhag['district'];?>">
											<?php echo $dzongkhag['district'];?>
										</option>
									<?php
									endforeach;
									?>
								</select>
				</div>
				<div class="form-group">
					<label for="location_type" class="control-label">Location Type</label>
					<select class="form-control" data-placeholder="Select" name="location_type" id="location_type" required >
									<option value=""></option>
										<?php
										foreach ($this->locationtypes as $location_type):
										?>
											<option value="<?php echo $location_type['location_type'];?>">
												<?php echo $location_type['location_type']; ?>
											</option>
										<?php 
											endforeach;
										?>
								</select> 
				</div>
				
				<div  class="form-group">
					<label for="status" class="control-label">Status</label>
					<div class="radio">
						<label>
							<input class="ace" type="radio" name="status" id="status" value="1" checked />
							<span class="lbl"> Yes </span>
						</label>
						<label>
							<input class="ace" type="radio" name="status" id="status" value="0" />
							<span class="lbl"> No </span>
						</label>
					</div>
				</div>
			</div>
		</div>
    </div> <!-- /modal-body -->
    <div class="modal-footer">
        <button type="submit" class="btn btn-success"><i class="fa fa-check"></i> Save </button>
        <button type="button" class="btn btn-warning" data-dismiss="modal" ><i class="fa fa-times"></i> Cancel </button> 
    </div>  
</form>
<script>
$('document').ready(function(){
	const fv = FormValidation.formValidation(document.getElementById('#form'), {
		fields: {
			department: {
				validators: {
					notEmpty: {
						message: 'Please provide department name.'
					}
				}
			},
			prefix: {
				validators: {
					notEmpty: {
						message: 'Please provide department prefix.'
					}
				}
			},
			status: {
				validators: {
					notEmpty: {
						message: 'Please select status.'
					}
				}
			},
		},
		plugins: {
			trigger: new FormValidation.plugins.Trigger(),
			bootstrap3: new FormValidation.plugins.Bootstrap3(),
			submitButton: new FormValidation.plugins.SubmitButton(),
			defaultSubmit: new FormValidation.plugins.DefaultSubmit(),
		},
	}).on('core.element.validated', function (e) {
		if (e.valid) {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-invalid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-valid');
		} else {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-valid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-invalid');
		}
	});
});
</script>