<?php
/**
 * View -- of Administration/UserController/changestyle
 * chophel@athang.com
 */
$this->headTitle($this->title);
?>
<?php foreach($users as $row);
$usercid=$this->userObj->getColumn($row['id'],'cid');
$ndiuser = $this->ndiObj->get(array('cid'=>$usercid,'status'=>1));
foreach ($ndiuser as $revoke);
?>
<form id="#form" method="post" action="<?php echo $this->url('user', array('action' =>'revoke')); ?>"  enctype="multipart/form-data" >                  
	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
		<h4 class="modal-title"> <i class="ace-icon fa fa-lock"></i> <?php echo $this->title.": ".$row['name']; ?></h4>
    </div>  <!-- /modal-header -->
    <div class="modal-body">  
		<div class="panel panel-default">
			<div class="panel-body">   
				<div class="row">
					<div class="col-lg-12">  
					    <input type="hidden" value="<?php echo $row['id'];?>" name="user_id" id="user_id" />
						<input type="hidden" value="<?php echo $revoke['id'];?>" name="revoke_id" id="revoke_id" />
						<div class="form-group">
							<label for="revocation_id" class="control-label">Revocation ID</label>
							<input type="revocation_id" class="form-control" name="revocation_id" id="revocation_id" value="<?php echo !empty($revoke['revocation_id'])? htmlspecialchars($revoke['revocation_id']) : '';?>" readonly />
						</div>
						<div class="form-group">
							<label for="revocation_status" class="control-label">Revocation Status</label>
							<select class="form-control" name="revocation_status" id="revocation_status" readonly>
								<option value="ACTIVE" <?php echo isset($revoke['revocation_status']) && $revoke['revocation_status'] === '1' ? 'selected' : ''; ?>>Active</option>
								<option value="SUSPENDED" <?php echo isset($revoke['revocation_status']) && $revoke['revocation_status'] === 'SUSPENDED' ? 'selected' : ''; ?>>Suspended</option>
								<option value="REVOKED" <?php echo isset($revoke['revocation_status']) && $revoke['revocation_status'] === 'REVOKED' ? 'selected' : ''; ?>>Revoked</option>
							</select>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div> <!-- /modal-body -->    
    <div class="modal-footer">
		<button type="submit" class="btn btn-success"><i class="ace-icon fa fa-key"></i>Save</button>
        <button type="button" class="btn btn-warning" data-dismiss="modal"><i class="ace-icon fa fa-times"></i>Cancel</button> 
    </div>
</form>
