<?php 
/**
 * View -- of Administration/UserController/usersAction
 * chophel@athang.com -- 2022
 */
	$this->headTitle($this->title);
?>
<?php echo $this->tabs_helper(array(402)); ?>
<div class="card">
	<div class="card-header">
		<div class="btn-group pull-right">
			<?php echo $this->button(2);?>
		</div>
	</div>
	<div class="table-responsive">
		<table id="datatable" class="d-style w-100 table text-dark-m1 text-95 border-y-1 brc-black-tp11 collapsed dtr-table">
                  <!-- add `collapsed` by default ... it will be removed by default -->
                  <!-- thead with .sticky-nav -->
         <thead class="sticky-nav text-primary-d1 text-uppercase text-100">
				<tr>
					<th >#</th>
					<th>Name</th>
					<th>CID</th>
					<th>Email</th>
					<th>Mobile</th>
					<th>Location</th>
					<th>Status</th>
					<?php if($this->button(1)!=""):?>
						<th class="no-print">Action</th>
					<?php endif; ?>
				</tr>
			</thead>
			<tbody>
			<?php $i=1+(($page-1)*25); foreach ($paginator as $row):?>
				<tr data-href="<?php echo $this->button(4,$row['id']); ?>">
					<td><?php echo $i++; ?> </td>
					<td><?php echo $row['name']; ?></td>
					<td><?php echo $row['cid']; ?></td>
					<td><?php echo $row['email']; ?></td>
					<td><?php echo $row['mobile']; ?></td>
					<td><?php echo $this->locationObj->getColumn($row['location'],'location'); ?></td>
					<td><?php echo $this->status($row['status']); ?></td>
					<?php if($this->button(1)!=""):?>
						<td><?php echo $this->button(1,$row['id']);?></td>
					<?php endif;?>
				</tr>
			<?php endforeach;?>
			</tbody>
		</table>
	</div>
	<div class="card-footer d-flex align-items-center justify-content-end">
		<?php echo $this->paginationControl($this->paginator,'Sliding','adm_pagination.phtml', 
			array('route' => 'user/paginator','action'=>'users','id'=>'0'));?>
	</div>
</div>
<script type="text/javascript">
$('document').ready(function(){
	$("tr[data-href]").each(function(){ 
		if($(this).attr('data-href')!='#'){
			$(this).css('cursor','pointer');
			$(this).bind('click',function() {
				window.document.location = $(this).attr("data-href");
			});
		}
	});
	$('#dataTables').DataTable();
});	
</script>