<?php 
/**
 * View -- of Administration/UserController/viewAction
 * chophel@athang.com
 */
	$this->headTitle($this->title);
?>
<?php foreach($users as $row);?>
<?php echo $this->tabs_helper(array(403,409,410),$row['id']); ?>
<div class="row mt-2 mt-md-4">
				<div class="col-12 col-md-4">
					<span class="profile-picture">
					<?php //echo 'https://www.citizenservices.gov.bt/BtImgWS/ImageServlet?type=PH&cidNo='.$row['cid'];?>
						<img class="img-responsive" alt="<?php echo $row['name']; ?>" id="avatar2" src="<?php echo $this->basePath() . '/images/avatar.jpg';?>" />
					</span>
					<div class="space space-4"></div>
					<?php echo $this->button(3, $row['id']);?>
					<?php echo $this->button(3, $row['id'],$row['status']);?>
					<div class="space space-6"></div>
					
					<div class="hr hr12 dotted"></div>
					<table class="table">
						<tr>
							<td>Locations Assigned</td>
							<td><?php $admin_location_array = explode(',', $row['admin_location']);
								echo sizeof($admin_location_array)."/".$this->locationObj->getCount(array('status'=>'1'));?></td>
						</tr>
						<tr>
							<td>Activities Assigned</td>
							<td><?php $admin_activity_array = explode(',', $row['admin_activity']);
								echo sizeof($admin_activity_array)."/".$this->activityObj->getCount(array('status'=>'1'));?></td>
						</tr>
						<tr>
							<td>No. of Logins</td>
							<td><?php echo $row['logins'];?></td>
						</tr>
					</table>
					<div class="hr hr16 dotted"></div>
				</div><!-- /.col -->

				<div class="col-12 col-md-8 mt-3 mt-md-0">
					<h4 class="blue">
						<span class="middle"><?php echo $row['name']; ?></span>
						<?php echo $this->status($row['status']);?>
					</h4>
					<table class="table">
						<tr>
							<td> Full Name </td>
							<td>
								<span><?php echo $row['name'];?></span>
							</td>
						</tr>
						<tr>
							<td> Citizen ID </td>
							<td>
								<span><?php echo $row['cid'];?></span>
							</td>
						</tr>
						<tr>
							<td> Date of Birth </td>
							<td>
								<span><?php echo $row['dob'];?></span>
							</td>
						</tr>
						<tr>
							<td> Location </td>
							<td>
								<span><?php echo $this->regionObj->getColumn($row['region'],'region');?></span>
								<span><?php echo $this->locationObj->getColumn($row['location'],'location');?></span>
							</td>
						</tr>
						<tr>
							<td> Email Address </td>
							<td>
								<span class=""><?php echo $row['email'];?></span>
							</td>
						</tr>
						<tr>
							<td> Mobile No. </td>
							<td>
								<span class="">+975-<?php echo $row['mobile'];?></span>	
							</td>
						</tr>
						<tr>
							<td> Roles </td>
							<td>
								<span class=""><?php $role_array = explode(',',$row['role']);
									for($i=0;$i<sizeof($role_array);$i++):?>
									<span class="label label-info label-white middle"><?php echo ($role_array[$i]!=0)?$this->rolesObj->getColumn($role_array[$i],'role'):'-';?></span>
									<?php endfor;?>
								</span>
							</td>
						</tr>
						<tr>
							<td> Location Access </td>
							<td>
								<span class="fst-italic fs-5 grey"><?php $location_array = explode(',',$row['admin_location']);
									for($i=0;$i<sizeof($location_array);$i++):
										echo ($location_array[$i]>0)?$this->locationObj->getColumn($location_array[$i],'location'):'-';
										echo ($i != sizeof($location_array)-1)?", ":"";
									endfor;?>
								</span>
							</td>
						</tr>
						<tr>
							<td> Activity Access </td>
							<td>
								<span class="fst-italic fs-5 grey"><?php $activity_array = explode(',',$row['admin_activity']);
									for($j=0;$j<sizeof($activity_array);$j++):
										echo ($activity_array[$j]>0)?$this->activityObj->getColumn($activity_array[$j],'activity'):'-';
										echo ($j != sizeof($activity_array)-1)?", ":"";
									endfor;?></span>
							</td>
						</tr>
					</table>
					<div class="profile-info-row">
							<div class="profile-info-name"> Joined </div>
							<div class="profile-info-value">
								<span class=""><?php echo $row['created'];?></span>
							</div>
						</div>
						<div class="profile-info-row">
							<div class="profile-info-name"> Last Login </div>
							<div class="profile-info-value">
								<span class=""><?php echo $row['last_login'];?></span>
							</div>
						</div>
						<div class="profile-info-row">
							<div class="profile-info-name"> Last Logout </div>
							<div class="profile-info-value">
								<span class=""><?php echo $row['last_logout'];?></span>
							</div>
						</div>
						<div class="profile-info-row">
							<div class="profile-info-name"> Last Accessed IP </div>
							<div class="profile-info-value">
								<span class=""><?php echo ($row['last_accessed_ip']=='::1')?'localhost-Dev':$row['last_accessed_ip'];?></span>
							</div>
						</div>
				</div><!-- /.col -->
			
		
</div><!-- /.row -->
<div class="modal fade" id="modal" tabindex="-1" role="dialog" aria-hidden="true">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
		</div><!-- /.modal-content -->
	</div><!-- /.modal-dialog -->
</div><!-- /.modal -->						