<?php
/**
 * Authentication --- forgotpwd
 * chophel@athang.com
 */
	$this->headTitle($title);
?> 
<style>
	.body-container {
		background-image: url(<?php echo $this->basePath() . '/images/pattern.jpg';?>);
	}
	.carousel-item > div {
		height: 100%;
		background-size: cover;
		background-repeat: no-repeat;
		background-position: center;
	}
</style>
<div class="p-2 p-md-4">
	<div class="row" id="row-1">
		<div class="col-12 col-xl-10 offset-xl-1 bgc-white shadow radius-1 overflow-hidden">
			<div class="row" id="row-2">
				<div id="id-col-intro" class="col-lg-5 d-none d-lg-flex border-r-1 brc-default-l3 px-0">
					<!-- the left side section is carousel in this demo, to show some example variations -->
					<div id="loginBgCarousel" class="carousel slide minw-100 h-100">
						<div class="carousel-inner minw-100 h-100">
							<div class="carousel-item active minw-100 h-100">
								<!-- default carousel section that you see when you open login page -->
								<div style="background-image: url(<?php echo $this->basePath() . '/images/bg_3.png';?>);" class="px-3 bgc-blue-l4 d-flex flex-column align-items-center justify-content-center">
									<a class="mt-5 mb-2 text-center" href="<?php echo $this->url('home');?>">
										<img class=" brc-white-tp1 radius-round" width="60%" src="<?php echo $this->basePath() . '/images/logo.png';?>" alt="Zhung Dratshang">
									</a>

									<h2 class="text-warning-d1">
										Dratshang <span class="text-80 text-dark-l1">EMIS</span>
									</h2>

									<div class="mt-auto mb-4 text-dark-tp2">
										Zhung Dratshang &copy; 2023
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>

				<div id="id-col-main" class="col-12 col-lg-7 py-lg-5 bgc-white px-0">
					<div class="tab-content tab-sliding border-0 p-0" data-swipe="right">

						<div class="tab-pane active show mh-100 px-3 px-lg-0 pb-3" id="id-tab-forgot" data-swipe-prev="#id-tab-login">
							<div class="position-tl ml-3 mt-2">
								<a href="<?php echo $this->url('auth', array('action' => 'login')); ?>" class="btn btn-light-default btn-h-light-default btn-a-light-default btn-bgc-tp">
								<i class="fa fa-arrow-left"></i>
								</a>
							</div>

							<div class="col-sm-10 offset-sm-1 col-md-8 offset-md-2 col-lg-6 offset-lg-3 mt-5 px-0">
								<h4 class="pt-4 pt-md-0 text-dark-tp4 border-b-1 brc-grey-l2 pb-1 text-130">
								<i class="fa fa-key text-brown-m1 mr-1"></i>
								Recover Password
								</h4>
							</div>

							<form id="#form" method="post" action="<?php echo $this->url('auth', array('action' => 'forgotpwd')); ?>" autocomplete="off" class="form-row mt-4">
								<div class="form-group col-sm-10 offset-sm-1 col-md-8 offset-md-2 col-lg-6 offset-lg-3">
									<label class="text-secondary-d3 mb-3">
										Enter your email address and we'll send you the instructions:
									</label>
									<div class="d-flex align-items-center">
										<input type="email" class="form-control form-control-lg pr-4 shadow-none" name="email" id="id-recover-email" placeholder="Email" required />
										<i class="fa fa-envelope text-grey-m2 ml-n4"></i>
									</div>
								</div>

								<div class="form-group col-sm-10 offset-sm-1 col-md-8 offset-md-2 col-lg-6 offset-lg-3 mt-1">
									<button type="submit" class="btn btn-orange btn-block px-4 btn-bold mt-2 mb-4">
										Continue
									</button>
								</div>
							</form>

							<div class="form-row w-100">
								<div class="col-12 col-sm-10 offset-sm-1 col-md-8 offset-md-2 col-lg-6 offset-lg-3 d-flex flex-column align-items-center justify-content-center">

									<hr class="brc-default-l2 mt-0 mb-2 w-100" />

									<div class="p-0 px-md-2 text-dark-tp4 my-3">
										<a class="text-blue-d1 text-600 btn-text-slide-x" href="<?php echo $this->url('auth', array('action' => 'login')); ?>">
											<i class="btn-text-2 fa fa-arrow-left text-110 align-text-bottom mr-2"></i>Back to Login
										</a>
									</div>

								</div>
							</div>
						</div>
					</div><!-- .tab-content -->
				</div>
			</div><!-- /.row -->
		</div><!-- /.col -->
	</div><!-- /.row -->
	<div class="d-lg-none my-3 text-dark-tp1 text-center">
		Zhung Dratshang &copy; 2023
	</div>
</div>