<?php
/**
 * Authentication --- login
 * chophel@athang.com
 */
?>
<style>
    html, body {
        height: 100%;
        margin: 0;
        display: flex;
        justify-content: center;
        align-items: center;
		background: none;
    }
    .centered-container {
        display: flex;
        justify-content: center;
        align-items: center;
        width: 100%;
        max-width: 600px;
        padding: 20px;
    }
    .container-content {
        width: 100%;
        background-color: #FFFFFF;
        padding: 20px;
        border-radius: 10px;
        box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);
        display: flex;
        flex-direction: column;
        justify-content: center;
        align-items: center;
        text-align: center;
    }
    .partition {
        width: 100%;
        height: 1px;
        background-color: #000; /* Adjust color as needed */
    }
    .NDI-QR {
        width: 200px;
        height: 200px;
        background-color: #F8F8F8;
    }
    .btn-custom {
        width: 158px;
        height: 30px;
        background-color: #5AC994;
        color: #FFFFFF;
        font-size: 12px;
        justify-content: center;
        border-radius: 30px;
        border: none;
        display: flex;
        align-items: center;
        padding: 0 10px;
        margin: 10px 0;
    }
    .btn-custom img {
        height: 20px;
        margin-left: 10px;
    }
    .small-img-download {
        width: 120px;
        height: 39px;
        cursor: pointer;
    }
    .small-img {
        width: 20px;
        height: auto;
    }
    .light-text {
        color: #999;
    }
    .hide-on-mobile {
        display: block;
    }
    .show-on-mobile {
        display: none;
    }
	.notification {
        position: fixed;
        bottom: 20px; /* Adjust as needed */
        right: 20px; /* Adjust as needed */
        color: #FFFFFF;
        padding: 10px 20px;
        border-radius: 5px;
        box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.2);
        display: none; /* Hidden by default */
        z-index: 1000; /* Ensure it's above other content */
    }
    .notification-success {
        background-color: #5AC994; /* Green for success */
    }
    .notification-error {
        background-color: #FF6F6F; /* Red for error */
    }
    @media (max-width: 600px) {
        .container-content {
            padding: 10px;
        }
        .btn-custom {
            width: 100%;
            font-size: 12px;
        }
        .hide-on-mobile {
            display: none;
        }
        .show-on-mobile {
            display: block;
        }
		.light-text {
		   font-size: 12px;
		}
    }
</style>
<div class="centered-container">
    <div class="container-content">
        <h2 class="text-warning-d1" style="font-size: 18px;">
            Dratshang <span class="text-20 text-dark-l1">EMIS</span>
        </h2>
        <div class="partition"></div>
        <div><p style="font-size: 18px; margin-bottom: 20px;">Scan with <span style="color: #5AC994;">Bhutan NDI</span> Wallet</p></div>
        <div style="position: relative;border: 1px solid #5AC994; padding: 1px; display: inline-block;margin-bottom: 20px;" class="">
            <img src="<?php echo $this->escapeHtml($this->QRcode); ?>" alt="QR Code">
            <img src="<?php echo $this->basePath() . '/images/NDI-DOX/ndilogo.png';?>" alt="Logo" style="position: absolute; width: 40px; height: 40px; top: 50%; left: 50%; transform: translate(-50%, -50%);">
        </div>
        <div class="light-text" style="margin-bottom: 20px;">
            <ol style="text-align: left;">
                <li>Open Bhutan NDI Wallet on your phone</li>
               <li>Tap the Scan button located on the menu bar <img class="small-img" src="<?php echo $this->basePath() . '/images/NDI-DOX/scanicon.png';?>" alt="Logo"><br>
                and capture code </li>
            </ol>
        </div>
        <div class="mobile-only-content" style="display: none;">
            <p>Open Bhutan NDI Wallet <a href='<?php echo $Deeplink;?>'style='text-decoration: underline;'>here</a></p>
        </div>
        <div style="margin-bottom: 20px;">
            <button type="button" class="btn-custom" onclick="window.location.href='https://www.youtube.com/watch?v=I6idRDRu-5Y'">
                Watch video guide <img src="<?php echo $this->basePath() . '/images/NDI-DOX/watchvideo.png';?>" alt="Logo">
            </button>
        </div>
        <div style="margin-bottom: 30px;">
            <label>Download Now!</label>
            <div style="display: flex; justify-content: space-between; gap: 10px;">
                <img class="small-img-download" src="<?php echo $this->basePath() . '/images/NDI-DOX/PlayStore.png';?>" alt="Download for android" onclick="window.location.href='https://play.google.com/store/search?q=bhutan%20ndi&c=apps&hl=en_IN&gl=US'">
                <img class="small-img-download" src="<?php echo $this->basePath() . '/images/NDI-DOX/AppStore.png';?>" alt="Download for apple" onclick="window.location.href='https://apps.apple.com/in/app/bhutan-ndi/id1645493166'">
            </div>
        </div>
        <div style="display: flex; justify-content: space-between;">
            <a href="<?php echo $this->url('auth', ['action' => 'login']); ?>">Back to Login</a>
        </div>
		<div id="notification" class="notification"></div> 
    </div>
</div>
<script>
$(document).ready(function() {
    function isMobileDevice() {
        return /Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent);
    }

    if (isMobileDevice()) {
        $('.mobile-only-content').show();
    }
	// Function to periodically check the proof status
    function postData() {
        var accessToken = "<?php echo $this->escapeHtml($this->accessToken); ?>";
        var reqThreadId = "<?php echo $this->escapeHtml($this->reqThreadId); ?>";

        // Debugging: Log values before sending the request
        console.log('AccessToken:', accessToken);
        console.log('ReqThreadId:', reqThreadId);

        $.ajax({
            url: '<?php echo $this->url('auth', array('action' => 'checkstatus'));?>',
            type: 'POST',
            data: {
                accessToken: accessToken,
                reqThreadId: reqThreadId
            },
            dataType: 'json',
            success: function(data) {
                // Log the entire response to debug
                console.log('Full response:', data);
                // Check if the response contains the expected structure
                if (data && data.status) {
                    //var status = response.status;
                    console.log('Status 1:', data.status);
                    
                    // Check different statuses and act accordingly
                    if (data.status === 'done') {
                        $('#notification')
                        .removeClass('notification-error') // Remove any previous error class
                        .addClass('notification-success') // Add success class
                        .html('You have successfully shared! Sent request to your NDI Wallet for issuance!')
                        .fadeIn().delay(5000).fadeOut();
                    } else if(data.status === 'abandoned'){
                        $('#notification')
                        .removeClass('notification-success') // Remove any previous success class
                        .addClass('notification-error') // Add error class
                        .html('User denied the share! Failed to issue credential')
                        .fadeIn().delay(5000).fadeOut();
                        console.log('Ending check. Status:', data.status);
                        return; // Exit the function to stop the retries
                    }else{
						setTimeout(postData, 5000); // Retry after a delay
					}
                } else {
                    console.log('ProofRequest is not yet shared by the user. Retrying...');
                    setTimeout(postData, 5000); // Retry after a delay
                }
            },
            error: function(xhr, status, error) {
                console.error(xhr.responseText); // Log the error message to the console
            }
        });
    }
    postData();
});
</script>
