<?php
/**
 * Authentication --- login
 * chophel@athang.com
 */
	$this->headTitle($title);
?> 
<style>
	.body-container {
		background-image: url(<?php echo $this->basePath() . '/images/pattern.jpg';?>);
	}
	.carousel-item > div {
		height: 100%;
		background-size: cover;
		background-repeat: no-repeat;
		background-position: center;
	}
	.btn-custom{
		background-color: #124143; 
		color: #F0F9F4;
		font-size: 18px;
		align-items: center;
		justify-content: center;
		border-radius: 10px;
	}
	.btn-custom img {
		height: 40px;
        margin-right: 10px;
    }
</style>
<div class="p-2 p-md-4">
	<div class="row" id="row-1">
		<div class="col-12 col-xl-10 offset-xl-1 bgc-white shadow radius-1 overflow-hidden">
			<div class="row" id="row-2">
				<div id="id-col-intro" class="col-lg-5 d-none d-lg-flex border-r-1 brc-default-l3 px-0">
					<!-- the left side section is carousel in this demo, to show some example variations -->
					<div id="loginBgCarousel" class="carousel slide minw-100 h-100">
						<div class="carousel-inner minw-100 h-100">
							<div class="carousel-item active minw-100 h-100">
								<!-- default carousel section that you see when you open login page -->
								<div style="background-image: url(<?php echo $this->basePath() . '/images/bg_3.png';?>);" class="px-3 bgc-blue-l4 d-flex flex-column align-items-center justify-content-center">
									<a class="mt-5 mb-2 text-center" href="<?php echo $this->url('home');?>">
										<img class=" brc-white-tp1 radius-round" width="60%" src="<?php echo $this->basePath() . '/images/logo.png';?>" alt="Zhung Dratshang">
									</a>

									<h2 class="text-warning-d1">
										Dratshang <span class="text-80 text-dark-l1">EMIS</span>
									</h2>

									<div class="mt-auto mb-4 text-dark-tp2">
										Zhung Dratshang &copy; 2023
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
				<div id="id-col-main" class="col-12 col-lg-7 py-lg-5 bgc-white px-0">
					<div class="tab-content tab-sliding border-0 p-0" data-swipe="right">
						<div class="tab-pane active show mh-100 px-3 px-lg-0 pb-3" id="id-tab-login">
							<!-- show this in desktop -->
							<div class="d-none d-lg-block col-md-6 offset-md-3 mt-lg-4 px-0">
								<h4 class="text-dark-tp4 border-b-1 brc-secondary-l2 pb-1 text-130">
								<i class="fa fa-coffee text-success-m1 mr-1"></i>
									Please Enter Your Credentials
								</h4>
							</div>

							<!-- show this in mobile device -->
							<div class="d-lg-none text-secondary-m1 my-4 text-center">
								<a href="<?php echo $this->url('home');?>">
									<img class=" brc-white-tp1 radius-round" width="25%" src="<?php echo $this->basePath() . '/images/logo.png';?>" alt="Zhung Dratshang">
								</a>
								<h1 class="text-170">
									<span class="text-warning-d1">
										Dratshang <span class="text-80 text-dark-tp3">EMIS</span>
									</span>
								</h1>
								Please Enter Your Credentials
							</div>


							<form id="#form" method="post" action="<?php echo $this->url('auth', array('action' => 'login')); ?>" autocomplete="off" class="form-row mt-4">
								<div class="form-group col-sm-10 offset-sm-1 col-md-8 offset-md-2 col-lg-6 offset-lg-3">
									<div class="d-flex align-items-center input-floating-label text-blue brc-blue-m2">
										<input placeholder="Username" type="text" class="form-control form-control-lg pr-4 shadow-none" name="username" id="username" required />
										<i class="fa fa-user text-grey-m2 ml-n4"></i>
										<label class="floating-label text-grey-l1 ml-n3" for="username">
											Username
										</label>
									</div>
								</div>


								<div class="form-group col-sm-10 offset-sm-1 col-md-8 offset-md-2 col-lg-6 offset-lg-3 mt-2 mt-md-1">
									<div class="d-flex align-items-center input-floating-label text-blue brc-blue-m2">
										<input placeholder="Password" type="password" class="form-control form-control-lg pr-4 shadow-none" name="password" id="password" required />
										<i class="fa fa-key text-grey-m2 ml-n4"></i>
										<label class="floating-label text-grey-l1 ml-n3" for="password">
											Password
										</label>
									</div>
								</div>


								<div class="col-sm-10 offset-sm-1 col-md-8 offset-md-2 col-lg-6 offset-lg-3 text-right text-md-right mt-n2 mb-2">
									<a href="<?php echo $this->url('auth', array('action' => 'forgotpwd')); ?>" class="text-primary-m1 text-95">
										Forgot Password?
									</a>
								</div>

								<div class="form-group col-sm-10 offset-sm-1 col-md-8 offset-md-2 col-lg-6 offset-lg-3">
									<label class="d-inline-block mt-2 mb-0 text-dark-l1">
										<input type="checkbox" class="mr-1" id="id-remember-me" />
										Remember me
									</label>
									
									<button type="submit" class="btn btn-danger btn-block px-4 btn-bold mt-2 mb-4">
										Sign In
									</button>
								</div>
								<div class="form-group col-sm-10 offset-sm-1 col-md-8 offset-md-2 col-lg-6 offset-lg-3">
								    <hr class="my-3">
									<button type="button" class="btn btn-custom btn-block px-4" onclick="window.location.href='<?php echo $this->url('auth', array('action' => 'ndilogin')); ?>'">
									    <img src="<?php echo $this->basePath() . '/images/NDI-DOX/UI_NDIlogo.png';?>" alt="Logo">
										Login with Bhutan NDI
										
									</button>
									<button type="button" class="btn btn-custom btn-block px-4" onclick="window.location.href='<?php echo $this->url('auth', array('action' => 'issuecredential')); ?>'">
									    <img src="<?php echo $this->basePath() . '/images/NDI-DOX/UI_NDIlogo.png';?>" alt="Logo">
										Receive Credential
									</button>
								</div>
							</form>
						</div>

					</div><!-- .tab-content -->
				</div>

			</div><!-- /.row -->
		</div><!-- /.col -->
	</div><!-- /.row -->
	<div class="d-lg-none my-3 text-dark-tp1 text-center">
		Zhung Dratshang &copy; 2023
	</div>
</div>