<?php
/**
 * 
 * View -- of Hr/LeaveController/indexAction
 * 
 */
$this->headTitle($this->title);
foreach($this->encashDtls as $row); 
foreach($this->employeeObj->get($row['employee']) as $emp);
$flag = false;
$subRoles = $this->userRoleObj->get(array('user'=>$this->userID, 'subrole'=>array('1','2','15','17')));  
if(sizeof($subRoles) >0 && sizeof($this->encashDtls)>0){
  $flag = true;
}else{	
   $userEmp = $this->usersObj->getColumn($this->userID, 'employee'); 
  if($userEmp == $row['employee'])
  {
	$flag = true;
  }					  
}
if($flag):
?>
<div class="row" id="report-print">
	<div class="col-lg-12">
		<div class="widget-box transparent ">
			<div class="widget-header widget-header-large">
			       <a class="btn btn-xs btn-danger" data-toggle="modal" data-target="#modal" 
				   href="<?php echo $this->url('acl', array('action' => 'activitylog', 'id' => "23-".$row['id'])); ?>" title="View Activity Logs">
							<i class="ace-icon fa fa-plus smaller-120" ></i>  
				   </a>
				   &nbsp;&nbsp;
				<h3 class="widget-title grey lighter">
					Leave Encashment Application &nbsp;&nbsp; <span class="orange">Dated:-<?php echo date('d-m-y',strtotime($row['encash_date']));?></span>
					&nbsp;&nbsp;<?php $this->status($row['status']); ?> 					
				</h3>
				<div class="widget-toolbar">
					<a class ="hidden-xs" style='cursor:pointer' id="print">
						<i class="ace-icon fa fa-file-pdf-o red"></i>
					</a>
					<?php //echo $this->button(3, $row['id']); ?>		
				</div>
			</div>
			<div class="widget-body">
				<div class="widget-main padding-12">
					<div id="report-print">
						<div class="row" id="convert-tb0">
							<div class="col-lg-8" id="convert-tb1">
								<ul class="list-unstyled spaced">
								    <li>
										<i class="ace-icon fa fa-caret-right blue"></i>
										Encashment Date : <b class="blue"><?php echo $row['encash_date']; ?></b>
									</li>
									<li>
										<i class="ace-icon fa fa-caret-right blue"></i>
										Employee Name | EID : <b class="blue"><?php echo $emp['full_name']." | ".$emp['emp_id']; ?></b>
									</li>
									<li>
										<i class="ace-icon fa fa-caret-right blue"></i>
										Location : <b class="blue"> <?php echo $emp['location']; ?></b>
									</li>	
									<li>
										<i class="ace-icon fa fa-caret-right blue"></i>
										Designation: <b class="blue"><?php echo $emp['designation']; ?> </b>
									</li>									
                                    <li>
								       <i class="ace-icon fa fa-caret-right blue"></i>
										Email | Contact No: <b class="blue"><?php echo $emp['email']; ?> | <?php echo $emp['mobile']; ?> </b>
									</li>		
								</ul>
							</div>
						</div>
						<div class="row">
						    <br/>
							<div class="col-lg-6">
							     <h4>Leave Encashment Details</h4>
								 <table class="table table-striped table-hover table-condensed">
								     <tr><th>Encashment Date</th><th>Total EL(Day/s)</th><th>No. of Encash Days</th><th>EL Balance(Day/s)</th></tr>
									 <tr>
									     <td><?php echo $row['leave_balance_date']; ?></td>
					                     <td><?php echo $row['no_of_encashed_days'] + $row['leave_balance']; ?></td>										 
										 <td><?php echo $row['no_of_encashed_days']; ?></td>
										 <td><?php echo $row['leave_balance']; ?></td>
									 </tr>
								 </table>
							</div>
						</div>
						<div class="row">
							<div class="col-lg-6">
							     <h4>Payment Details</h4>
								 <table class="table table-striped table-hover table-condensed">
								     <tr><th>Gross Salary</th><th>PID Deduction</th><th>Payable Amount</th></th></tr>
									 <tr>
									     <td><?php echo $this->currency($row['payment_amount'] + $row['deduction']); ?></td>
					                     <td><?php echo $this->currency($row['deduction']); ?></td>										 
										 <td><?php echo $this->currency($row['payment_amount']); ?></td>										
									 </tr>
								 </table>
							</div>
						</div>
						<div class="row">
							<div class="col-lg-12">
								<ul class="list-unstyled spaced">
									<li>
										<i class="ace-icon fa fa-caret-right blue"></i>Remarks: <b class="red"><?php echo $row['remarks'];?> </b>
									</li>
								</ul>
							</div>
						</div>		
						<br/> &nbsp;
					<!-- Upload and Download file attachments -->			
					<?php   
					 echo $this->partial('partial/attachment.phtml', array('process' => '23', 'process_id'=> $row['id'] , 'status' => $row['status']));
					?>					
				    <!-- End of attachment -->
					<div class="row">
					 <form method="post" action="<?php echo $this->url('leave', array('action' => 'encashmentdtl')); ?>">	
					    <div class="col-lg-8">
						   &nbsp;
						</div>
						<div class="col-lg-4"><br/>&nbsp;
						<?php
						  $employeeUser = $this->usersObj->getColumn(array('employee'=>$emp['id']), 'id');	
						  $activity = $this->leaveFlowObj->getMax($column='activity', $where=array('application'=>$row['id'], 'process'=>'23'));
						  $flows = $this->leaveFlowObj->get(array('application'=>$row['id'],'activity'=>$activity, 'process'=>'23'));
						  //foreach($flows as $flow);	
						?>
					    <?php if($row['status'] == "1" && ($this->userID == $employeeUser || $this->userID == $row['author'])):  ?>					       
							       <form method="post" action="<?php echo $this->url('leave', array('action' => 'leavedetail')); ?>">	
									<a data-toggle="modal" data-target="#modal" href="<?php echo $this->url('leave', array('action'=>'encashprocess', 'id'=>$row['id'].'-1'));?>" class="btn btn-success"> 
									<i class="fa fa-check-square-o"></i> Apply Encashment </a>								
									<input type="hidden" value="<?php echo $row['id']; ?>" name="application_id">									
									<button type="submit" value="1" name="cancel" class="btn btn-danger" onClick="return confirm('Are you sure to Cancel this leave?')"> 
									<i class="fa fa-times"></i> Cancel  </button>
																	
                                </form>		
					      <?php elseif(in_array($row['status'],array('2','5'))):							      
								   foreach($flows as $flow);
								   if($this->userID == $flow['routing']):
									   $buttons = explode('|',$flow['action']); 
									   for($i=0;$i<count($buttons);$i++):	
										  $leaveActions = $this->leaveActionObj->get($buttons[$i]); 
										  foreach($leaveActions as $leaveAction);	
										  ?>
										  <a data-toggle="modal" data-target="#modal" href="<?php echo $this->url('leave', array('action'=>'encashprocess', 'id'=>$row['id']."-".$leaveAction['id']));?>"  class="btn btn-<?php echo $leaveAction['label']; ?>"> 
										    <?php echo $leaveAction['action']; ?>
										  </a>
										  <?php
									   endfor;
									endif;
							  endif;  ?>
                        </div>
					 </form>	
					</div>	
                </div>					
		     </div>				
	     </div>
      </div>
	</div>
</div>
<?php endif; ?>
<div id="modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
		</div>
	</div>
</div>