<div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title"> <i class="fa fa-asterisk"></i> Action </h4>
</div>  <!-- /modal-header -->

<div class="modal-body">
	<div class="panel panel-default">
		<div class="panel-body">      
	    <form method="post" action="<?php echo $this->url('leave', array('action' => 'process')); ?>">					
	     <?php
	        $variables = explode('-', $this->id);
			$applicationID = $variables['0'];
			$action = $variables['1'];
			$leaveFlow = $this->leaveFlowObj->get(array('application'=>$applicationID));
			$actors = array();
			foreach($leaveFlow as $flow):			 
			   if(!in_array($flow['actor'],$actors)){			   
			      array_push($actors, $flow['actor']);				 
			   }
			endforeach;
			switch($action):
			    case 1: ?>
				         <div class="form-group">
							 <label for="leave Official" class="control-label">Supervisor</label>
							 <select class="form-control" id="routing" name="routing" >
								<option value=""></option>								
								 <?php foreach($this->users as $user): ?>
							       <option value="<?php echo $user['id'];?>"> <?php echo $user['name']; ?> </option>
							     <?php endforeach; ?>
							</select>
						</div>
				        <?php
						$button_label = "Apply";
						$label = "success";
						break;
			    case 2: //Forward the app
				        ?>
						 <div class="form-group">
			              <label for="routing" class="control-label">Forward To:</label>
						  <select class="form-control" id="routing" name="routing" >
						     <option value="">-select-</option>
							 <?php 
								$leaveOfficials = $this->userRoleObj->get(array('subrole'=>'17'));							
								foreach ($leaveOfficials as $officail):
								$userDtls = $this->userObj->get($officail['user']);
								foreach($userDtls as $userdtl);
								?>
									<option value="<?php echo $userdtl['id'];?>"><?php echo $userdtl['name'];?></option>
								<?php
								endforeach;
							 ?>						    
						  </select>
						 </div>
						<?php
						$button_label = "Forward";
						$label = "info";
						break;  
                case 3: //Application Approve 
				        $button_label = "Approve";
						$label = "success";
				        break;				
				case 4: //Reject Application
				        $button_label = "Reject";
						$label = "danger";
				        break;
				case 5: //Send App back 
				        $button_label = "Send-Back";
						$label = "warning";						
				        ?>
						<div class="form-group">
			              <label for="routing" class="control-label">Send Back To:</label>
						  <select class="form-control" id="routing" name="routing" >
						     <option value="">-select-</option>
						      <?php 
							   for($i=0; $i < count($actors); $i++){
							    if($actors[$i] != $this->userID) {
							      $userDtls = $this->userObj->get($actors[$i]);
								  foreach($userDtls as $dtl):
								     ?>
									   <option value="<?php echo $dtl['id']; ?>"><?php echo $dtl['name']; ?></option>
									 <?php
								  endforeach;
								}
							   }
							 ?>  
						</select>
						</div>
						<?php break;
				case 7: //Send App back 
				        $button_label = "Leave Completed";
						$label = "warning";	   ?>
						<div class="form-group">
								<label for="reporting_date" class="control-label">Reporting Date</label>
								<div class="date input-group" id="reporting_date" data-date="<?php echo date('Y-m-d');?>" data-date-format="yyyy-mm-dd" >
									<input class="form-control span2" name="reporting_date" id="reporting_date" type="text" placeholder="Reporting Date" readonly required>
									<span class="input-group-addon add-on"><i class="fa fa-calendar"></i></span>
								</div>
						</div>
						<div class="form-group">
								<label for="reporting_date" class="control-label">Actual leave taken(Days)</label>
								<input class="form-control span2" name="actual_leave_taken" id="actual_leave_taken" type="text" placeholder="actual_leave_taken" required>
								
						</div>
				        <?php
						break;
			endswitch;
	     ?>
		<input type="hidden" value="<?php echo $action; ?>" name="action">
		<input type="hidden" value="<?php echo $applicationID; ?>" name="application">
		<div class="form-group">
			<label for="remarks" class="control-label">Remarks</label>
			<textarea class="form-control" rows="3" name="remarks" required>
			</textarea>
		</div>
		<div class="form-group">
		   <input type="submit" value="<?php echo $button_label; ?>" class="btn btn-<?php echo $label;?>">
		</div>
	    </form>
	  </div>
	</div>	
</div>
<script>
	$('#reporting_date').datepicker();
	$('document').ready(function(){
		$('form select').chosen({ allow_single_deselect: true });
		$('form').formValidation({
			excluded: ':disabled',
			message: 'Please enter a value.',
			fields: {
				remarks: {
					validators: {
						notEmpty: {
							message: 'Please provide remarks.'
						}
					}
				},
				routing: {
					validators: {
						notEmpty: {
							message: 'Please select person to route.'
						}
					}
				},
			}
		});
	});
</script>
